---
title: "Assignment 05 R"
author: "Robert Schütz"
date: "`r Sys.Date()`"
output: html_document
---

# General

Github-Projekt URL: https://github.com/Borschu/Assignment_05

Install / load packages:
```{r}

#install.packages("httr")
library("httr")

library("tidyverse")

#install.packages("magrittr")
library("magrittr")

library("maps")
```

# Getting to know the API

Limit: 5000 API calls per day
rate limit: 5 requests per second

```{r}
# read file for api key
source("C:/Users/schur/OneDrive/Dokumente/Studium/Data Science Master Tübingen/1. Semester/Data Science Project Management/Assignment/key_assignment_5.R")
```

# Interacting with the API - the basics

## (7)
```{r}
# search for all venues in Germany (where countryCode = DE)
res_venue_ger <- GET(url = "https://app.ticketmaster.com/discovery/v2/venues/",
                     query = list(apikey = ticketmaster_key,
                                  "countryCode" = "DE"))

# print content of the query
con_venue_ger <- content(res_venue_ger)
con_venue_ger
```

## (8)

```{r}
## name
name <- map_chr(con_venue_ger$`_embedded`$venues, "name")

## city
# create empty city-vector
city <- c()
# loop over all 20 venues
for (i in 1:20){
  # add name to city vector
  city <- append(city, con_venue_ger$`_embedded`$venues[[i]]$city$name)
}


## postal code 
# create posal code vector (map_dbl doesnt work), default to 
postalCode <- as.double(map_chr(con_venue_ger$`_embedded`$venues, "postalCode", .default = NA))


## address
# create empty adress vector
address <- c()
# append values via loop
# if there is no such value create NA
for (i in 1:20){
  address <- append(address, ifelse(is.null(con_venue_ger$`_embedded`$venues[[i]]$address$line1),
                                    NA, con_venue_ger$`_embedded`$venues[[i]]$address$line1))
}

## url 
# create url vector
url <- map_chr(con_venue_ger$`_embedded`$venues, "url")

## longitude 
# create empty longitude-vector
longitude <- c()
# loop over all 20 venues
# if the value doesn exist ->NA, else append by the specific value
for (i in 1:20){
  # add name to longitude vector
  longitude <- append(longitude, ifelse(is.null(con_venue_ger$`_embedded`$venues[[i]]$location$longitude),
                                    NA, con_venue_ger$`_embedded`$venues[[i]]$location$longitude))
}
# change datatype to double
longitude <- as.double(longitude)

## latitude
# create empty latitude-vector
latitude <- c()
# loop over all 20 venues
# if the value doesn exist ->NA, else append by the specific value
for (i in 1:20){
  # add name to longitude vector
  latitude <- append(latitude, ifelse(is.null(con_venue_ger$`_embedded`$venues[[i]]$location$latitude),
                                    NA, con_venue_ger$`_embedded`$venues[[i]]$location$latitude))
}
# change datatype to double
latitude <- as.double(latitude)

# create dataframe
venue_ger <- data.frame(name, city, postalCode,address, url, longitude, latitude)

# das folgede könnte man nutzen um die 20 zu ersetzen, damit diese nicht hard gecoded ist
#con_venue_ger$page$size
```

# Interacting with the API - advanced

```{r}
# determine how many pages exist
con_venue_ger$page$totalPages
## 238

#res_venue_ger_238 <- GET(url = "https://app.ticketmaster.com/discovery/v2/venues/",
#                     query = list(apikey = ticketmaster_key,
#                                  "countryCode" = "DE",
#                                  "page" = 238))
#content(res_venue_ger_238)

create_df <- function(countryCode){
  page <- GET(url = "https://app.ticketmaster.com/discovery/v2/venues/",
                     query = list(apikey = ticketmaster_key,
                                  "countryCode" = countryCode))
  Sys.sleep(0.2)
  con_page <- content(page)
  nr_pages <- con_page$page$totalPages
  nr_entries <- con_page$page$size
  
  #name <- c()
  #city <- c()
  #postalCode <- c()
  #address <- c()
  #url <- c()
  #longitude <- c()
  #latitude <- c()
  
  df_all <- data.frame(name = character(), 
                       city = character(), 
                       postalCode = double(),
                       address = character(), 
                       url = character(), 
                       longitude = double(), 
                       latitude = double())
  
  for (p in 0:nr_pages){
    
    page <- GET(url = "https://app.ticketmaster.com/discovery/v2/venues/",
                     query = list(apikey = ticketmaster_key,
                                  "countryCode" = countryCode,
                                  "page" = p))
    content = content(page)
    
    ## name
name <- map_chr(content$`_embedded`$venues, "name", .default = NA)
#print(name)
## city
# create empty city-vector
city <- c()
# loop over all 20 venues
for (i in 1:nr_entries){
  # add name to city vector
  city <- append(city, ifelse(is.null(content$`_embedded`$venues[[i]]$city$name),NA,
                              content$`_embedded`$venues[[i]]$city$name))
}


## postal code 
# create posal code vector (map_dbl doesnt work), default to prevent error if value is missing
postalCode <- as.double(map_chr(content$`_embedded`$venues, "postalCode", .default = NA))


## address
# create empty adress vector
address <- c()
# append values via loop
# if there is no such value create NA
for (i in 1:nr_entries){
  address <- append(address, ifelse(is.null(content$`_embedded`$venues[[i]]$address$line1),
                                    NA, content$`_embedded`$venues[[i]]$address$line1))
}

## url 
# create url vector
url <- map_chr(content$`_embedded`$venues, "url", .default = NA)

## longitude 
# create empty longitude-vector
longitude <- c()
# loop over all 20 venues
# if the value doesn exist ->NA, else append by the specific value
for (i in 1:nr_entries){
  # add name to longitude vector
  longitude <- append(longitude, ifelse(is.null(content$`_embedded`$venues[[i]]$location$longitude),
                                    NA, content$`_embedded`$venues[[i]]$location$longitude))
}
# change datatype to double
longitude <- as.double(longitude)

## latitude
# create empty latitude-vector
latitude <- c()
# loop over all 20 venues
# if the value doesn exist ->NA, else append by the specific value
for (i in 1:nr_entries){
  # add name to longitude vector
  latitude <- append(latitude, ifelse(is.null(content$`_embedded`$venues[[i]]$location$latitude),
                                    NA, content$`_embedded`$venues[[i]]$location$latitude))
}
# change datatype to double
latitude <- as.double(latitude)
print(p)
# create dataframe
df_page <- data.frame(name, city, postalCode,address, url, longitude, latitude)

df_all <- rbind(df_all, df_page)
#print("hello world 2")
#
Sys.sleep(1.5)

  }
  
  return(df_all)
}

venue_de <- create_df("DE")

# print head of dataframe
print(head(venue_de,10))
print(dim(venue_de))

```

# Visualizing the extracted data

## (10)
```{r}
# based on the code that is mentioned in the assignment 
ggplot(venue_ger) +
borders("world", "Germany", colour = "black", fill = "grey90") +
  # add geom_point to create points for the locations
  # add alpha to make points transparent (-> to make overlaying points visible)
  geom_point(aes(longitude,latitude),
             alpha = 0.4)+
theme_void() +
coord_quickmap() +
labs(title = "Event locations across Germany",
caption = "Source: ticketmaster.com") +
theme(title = element_text(size=8, face='bold'),
plot.caption = element_text(face = "italic"))
```

## (11)
```{r}
# create NAs for latitude / longitude if  outside from germany
# write a function to make life easier for the next tasks

adapt_long_lat <- function(df_country,long_lower,long_upper,lat_lower,lat_upper){
  df_country$longitude <- ifelse(df_country$longitude < long_lower, NA, df_country$longitude)
  
  df_country$longitude <- ifelse(df_country$longitude > long_upper, NA, df_country$longitude)
  
  df_country$latitude <- ifelse(df_country$latitude < lat_lower, NA, df_country$latitude)
  
  df_country$latitude <- ifelse(df_country$latitude > lat_upper, NA, df_country$latitude)
  
  return(df_country)
}

#longitude is outside the range (5.866, 15.042) or
#where the value of latitude is outside the range (47.270, 55.059)
venue_de_adjust <- adapt_long_lat(venue_ger,5.866, 15.042,47.270, 55.059)


# visualize venues with adapted longitude /latitude

ggplot(venue_de_adjust) +
borders("world", "Germany", colour = "black", fill = "grey90") +
  # add geom_point to create points for the locations
  # add alpha to make points transparent (-> to make overlaying points visible)
  geom_point(aes(longitude,latitude),
             alpha = 0.4)+
theme_void() +
coord_quickmap() +
labs(title = "Event locations across Germany",
caption = "Source: ticketmaster.com") +
theme(title = element_text(size=8, face='bold'),
plot.caption = element_text(face = "italic"))
```


# Event locations in other countries

## (12)

```{r}
# adjust the following code if its clear why the function thrwos errors

venue_de <- create_df("DE")

venue_de_adjust <- adapt_long_lat(venue_ger,5.866, 15.042,47.270, 55.059)


# visualize venues with new 

ggplot(venue_de_adjust) +
borders("world", "Germany", colour = "black", fill = "grey90") +
  # add geom_point to create points for the locations
  # add alpha to make points transparent (-> to make overlaying points visible)
  geom_point(aes(longitude,latitude),
             alpha = 0.4)+
theme_void() +
coord_quickmap() +
labs(title = "Event locations across Germany",
caption = "Source: ticketmaster.com") +
theme(title = element_text(size=8, face='bold'),
plot.caption = element_text(face = "italic"))

```

